### PR TITLE
Delay initializing the router until it is installed or manually started

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Because global hooks need to be defined on the router AFTER it is created it is problematic that the initial route is set immediately on creation. This can cause race conditions and import issues with other modules. 

By replacing the `initialized` property of the router with a `start` method and then automatically calling `start` when the router is installed we can make sure that the user is able to define global hooks and have them run on that initial route while avoiding module errors. 

Closes https://github.com/kitbagjs/router/issues/269

### CODE REVIEW

**Review by stackoverfloweth — APPROVED** [review]
This is great and all, but don't we want to add an option to `createRouter` that prevents automatic calling of start? Seems like that defeats the purpose if dev wants to control when it starts?

**Comment by stackoverfloweth** [comment]
Also, does this close https://github.com/kitbagjs/router/issues/269?

**Comment by pleek91** [comment]
> This is great and all, but don't we want to add an option to `createRouter` that prevents automatic calling of start? Seems like that defeats the purpose if dev wants to control when it starts?

My thought is once it's installed it can start, we could add an option to prevent auto starting. But the main issue was starting immediately before it was even being used.

**Comment by stackoverfloweth** [comment]
> > This is great and all, but don't we want to add an option to `createRouter` that prevents automatic calling of start? Seems like that defeats the purpose if dev wants to control when it starts?
> 
> My thought is once it's installed it can start, we could add an option to prevent auto starting. But the main issue was starting immediately before it was even being used. 

Oh that makes sense. I missed the part where the `start()` call was inside `install`. I thought it was just inside of `createRouter`

**Pull request merged**
